layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: false
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  linkedin: anurag0022
  medium: @anurag0022
  stackoverflow: 9821453
  # twitter: your_username
  # youtube: your_username

topics:
  - name: Android
    web_url: https://github.com/topics/android
    image_url: https://www.android.com/static/2016/img/logo-android-green_2x.png

 - name: React native
   web_url: https://github.com/topics/react-native
   image_url: https://facebook.github.io/react-native/img/header_logo.png

  - name: User Experience

  # - name: Sass
    # web_url: https://github.com/topics/sass
    # image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
